from .index_page import render_index
from .matrix_page import render_matrix
from .history_page import render_history
from .health_page import render_health
from .lab_page import render_lab
from .settings_page import render_settings
from .app_page import render_app_pages
from .apps_page import render_apps_index
from .badge_page import render_badge_pages
from .app_history_page import render_app_history_pages
from .badges_page import render_badges